# Generated by Django 5.2.3 on 2025-09-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinfo',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos/'),
        ),
    ]
