# Generated by Django 5.2.3 on 2025-09-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appinfo_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppInfo',
            new_name='GramPanchayatInfo',
        ),
    ]
