# Generated by Django 5.2.3 on 2025-09-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_appinfo_grampanchayatinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grampanchayatinfo',
            name='version',
        ),
        migrations.AddField(
            model_name='grampanchayatinfo',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
