# Generated by Django 5.2.3 on 2025-09-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_grampanchayatinfo_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='slideshow/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
