# Generated by Django 5.2.3 on 2025-09-29 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_aboutvillage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutvillage',
            old_name='about_village',
            new_name='content',
        ),
    ]
