# Generated by Django 5.2.3 on 2025-10-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_about_village_aboutvillage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionObjectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=300)),
                ('missions', models.JSONField(blank=True)),
            ],
        ),
    ]
