# Generated by Django 5.2.3 on 2025-10-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_missionobjectives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionobjectives',
            name='missions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
