# Generated by Django 5.2.3 on 2025-10-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_missionobjectives_missions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='missionobjectives',
            name='missions',
        ),
        migrations.AddField(
            model_name='missionobjectives',
            name='missions',
            field=models.ManyToManyField(blank=True, related_name='objectives', to='api.mission'),
        ),
    ]
