# Generated by Django 5.2.3 on 2025-10-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_importantlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantlinks',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
