# Generated by Django 5.2.3 on 2025-10-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_department_governmentgr'),
    ]

    operations = [
        migrations.CreateModel(
            name='GramPanchayatDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='gp_documents/')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('date_issued', models.DateField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
