# Generated by Django 5.2.3 on 2025-10-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_photogallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrampanchayatBodies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='bodies_photos/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaharastraOfficers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='maharastra_officers_photos/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TorsoleVillagePopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_year', models.IntegerField()),
                ('to_year', models.IntegerField()),
                ('vilage_name', models.CharField(blank=True, max_length=200)),
                ('family_count', models.IntegerField()),
                ('population', models.IntegerField()),
            ],
        ),
    ]
